### ISSUE TITLE
Using react-native-quick-actions on < iOS 9 crashes the container app

### ISSUE THREAD

**Issue by sevachon** [madriska/react-native-quick-actions#19]
I see that the react-native-quick-actions is only supported on iOS 9+, which is expected since this functionality was only added to the iOS 9 SDK (e.g. UIApplicationShortcutItems). However, I would expected the plugin to do nothing on downlevel versions, instead of crashing.

**Comment by kemcake** [comment]
@sevachon You can try this: https://github.com/madriska/react-native-quick-actions/pull/11
This has been reverted here: https://github.com/madriska/react-native-quick-actions/commit/1f2a40b4c6eb2d17c768241b45b1613437073d91#comments

Please tell us if it works well for you 🙌

**Comment by jordanbyron** [comment]
@sevachon also see #12. If you have any iOS development experience supporting multiple versions I'd happily review a PR that adds backwards compatibility without introducing excessive complexity. Until then I don't think there is much we can do as this is a road we've already been down with no success. Sorry 😞
