### ISSUE TITLE
Feature request: Custom icons

### ISSUE THREAD

**Issue by superandrew213** [madriska/react-native-quick-actions#21]
It would be good if you could set custom icons. Will look into implementing it soon.

**Comment by kemcake** [comment]
@superandrew213 Actually, you can do it by adding your icons directly to the xcode project `Images.xcasset` and referecing them by their name: 

```
QuickActions.setShortcutItems([
      { 
        type: 'Notifications', title: 'notifications',
        icon: 'ic-notifications-default-60',
        userInfo: { },
      },
     ...
]);
```

**Comment by superandrew213** [comment]
@kemcake awesome! Thanks

**Comment by alpamys-qanybet** [comment]
@superandrew213, @kemcake, hi there, what about defining in ```Info.plist``` statically?

**Comment by jordanbyron** [comment]
@alpamys-qanybet RTM:

https://github.com/jordanbyron/react-native-quick-actions#adding-static-quick-actions---ios-only
