### ISSUE TITLE
Listener does not trigger when app is started using 3d touch

### ISSUE THREAD

**Issue by superandrew213** [madriska/react-native-quick-actions#23]
Listener does not trigger when app is started. Only if app is running in background.

**Comment by jordanbyron** [comment]
@superandrew213 it sounds like you missed this line from the README:

> To get any actions sent when the app is cold-launched using the following code:

```javascript
var QuickActions = require('react-native-quick-actions');
var action = QuickActions.popInitialAction();
if (action) {
  doSomethingWithTheAction(action); // e.g. LinkingIOS.openURL(..)
}
```

**Comment by superandrew213** [comment]
@jordanbyron sure did. Thanks!

**Comment by messense** [comment]
Tried this, still not working. Added some logs in objective-c code:

```
Nov 14 12:05:49 messenses-MBP riskstorm[2466] <Notice>: [RNQuickAction] Quick action shortcut item pressed: com.riskstorm.riskstorm.search
Nov 14 12:05:49 messenses-MBP riskstorm[2466] <Warning>: Quick action initialAction: (null)
```

https://github.com/madriska/react-native-quick-actions/blob/master/RNQuickAction/RNQuickAction/RNQuickActionManager.m#L54

`_initialAction` is null.

**Comment by jordanbyron** [comment]
@messense initial action is only populated when the app is started for the first time, not when it is already running in the background. Instead you should use `DeviceEventEmitter.addListener('quickActionShortcut', function(data) {})` to respond to quick actions while the app is loaded.

Also keep in mind that once you call `QuickActions.popInitialAction()`, subsequent calls to that function will NOT return the initial action again, hence the name **pop**InitialAction.

Without seeing any code I can only guess as to why this isn't working for you. I've been using `popInitialAction` in my RN app for a while now with great success.

**Comment by messense** [comment]
@jordanbyron My code is like:

```javascript
  componentDidMount() {
    if (Platform.OS == 'ios') {
      QuickActions.isSupported((error, supported) => {
        if (!supported) {
          return;
        }
        let action = QuickActions.popInitialAction();
        if (action) {
          this._handleQuickActions(action);
        }
        DeviceEventEmitter.addListener(
          'quickActionShortcut',
          this._handleQuickActions.bind(this)
        );
      });
    }
  }
```

**Comment by messense** [comment]
@jordanbyron I am using [react-native-navigation](https://github.com/wix/react-native-navigation) with a tab based App, I am not sure where/when I should call `QuickActions.popInitialAction()`.

**Comment by jordanbyron** [comment]
@messense could you create and share a simple example app that demonstrates that the problem with the `popInitialAction` function? From what I can tell your app has a lot of moving parts and it may be helpful to see a simplified example and go from there. Thanks!

**Comment by messense** [comment]
@jordanbyron Never mind. Got it working now.

**Comment by zhouanbo** [comment]
@messense Could you share how did you get it to work? I'm also using react-native-navigation here and I'm also having null as the initial action.

**Comment by messense** [comment]
@zhouanbo The trick is to call `QuickActions.popInitialAction` before start navigation.

```javascript
    let initialQuickAction = null;
    if (Platform.OS == 'ios') {
      const QuickActions = require('react-native-quick-actions');
      initialQuickAction = QuickActions.popInitialAction();
    }
    Navigation.startTabBasedApp({...})
```

**Comment by ozsirma** [comment]
I used react-native-navigation but initialQuickAction is null.  I use it the same way.
