### ISSUE TITLE
React / RCTBridge.h not found in my project

### ISSUE THREAD

**Issue by xuanheScript** [madriska/react-native-quick-actions#29]
![image](https://cloud.githubusercontent.com/assets/19216775/22623516/8955f726-eb98-11e6-81f8-eeb95db7fd67.png)
I see someone experiencing a similar problem, I tried changing my headpath but did not succeed if I changed
![image](https://cloud.githubusercontent.com/assets/19216775/22623524/e6669c90-eb98-11e6-8bb2-dc7ce5d3d9ff.png)

**Comment by jordanbyron** [comment]
@xuanheScript are you running React Native v0.40+? If not then you need to downgrade version v0.1.5 or lower of this app.

**Comment by adiagr95** [comment]
I'm using React native 0.40+, still facing the same error. I've already tried everything possible.

**Comment by hamoudaarfaoui** [comment]
same error RN0.61
