### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by pietropizzi** [madriska/react-native-quick-actions#35]
This is more of a question than an issue.

Could you point me to what would have to change to make this iOS 8 compatible. And I don't mean that the feature has to work, just to prevent the app from crashing.

I could work an a PR if you give me some pointers.

**Comment by jordanbyron** [comment]
Hi @pietropizzi! Take a look at #12 and #19. This is something we've attempted to do before but never made much progress. Good luck! Let me know if you have any questions. I'll keep this ticket open for a while.
