### ISSUE TITLE
Exception on Android < 7 (nougat)

### ISSUE THREAD

**Issue by Pollizzio** [madriska/react-native-quick-actions#39]
Hi,
I cannot run my App that imports QuickAction on Android < 7. I got the following exception:
C++ Exception in 'NativeModules': java.lang.NoClassDefFoundError: android.content.pm.ShortcutManager
<unknown>
    index.android.js:1
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107

I'm aware that quick action are available starting 7 but I expect to not have exceptions while using the same code.

edit: I'm using v0.3.3 on Android api 23.

**Comment by jordanbyron** [comment]
Hey @Pollizzio,

As you pointed out we only support Android 7+ so if you need to target older version of Android you won't be able to use this library. Sorry.
