### ISSUE TITLE
Missing context for method declaration

### ISSUE THREAD

**Issue by gsdias** [madriska/react-native-quick-actions#42]
Hi, I followed all steps to install and link all dependencies but after putting the code in AppDelegate.m I get the following error:
![image](https://user-images.githubusercontent.com/1720784/28735277-8cde4840-73f5-11e7-921f-b946045b3a19.png)

Any help appreciated.

**Comment by jordanbyron** [comment]
Hey @gsdias!

I think the problem is that you need to define that method after the `@implementation AppDelegate` line and before the `@end` statement in your `AppDelegate.m` file. See the example below:

```obj-c
#import "AppDelegate.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"
#import "RNQuickActionManager.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // SNIP
}

- (void)application:(UIApplication *)application performActionForShortcutItem:(UIApplicationShortcutItem *)shortcutItem completionHandler:(void (^)(BOOL succeeded)) completionHandler {
  [RNQuickActionManager onQuickActionPress:shortcutItem completionHandler:completionHandler];
}

@end
```

Our README could be clearer about that. Let me know if that resolves your issue 🚒

**Comment by gsdias** [comment]
Hi @jordanbyron, yes I manage to find the same solution. Including that code inside implementation AppDelegate fixes the problema and works just fine. Tks.
