### ISSUE TITLE
[Android] Can not receive message from popInitialAction

### ISSUE THREAD

**Issue by Lxxyx** [madriska/react-native-quick-actions#46]
code:

```
  QuickActions
    .popInitialAction()
    .then(handleEvents)
```

iOS is ok, but android failed.

Android Version 7.1

android:launchMode="singleTop"

**Comment by jordanbyron** [comment]
Hi @Lxxyx, How did that action fail in your Android build? Was there an exception thrown? Any more details would really help us out. Thanks!

**Comment by Lxxyx** [comment]
@jordanbyron I fixed by just now.

When android, popInitialAction will only return data contains type.

Like:

```
{
  type: 'orders'
}
```

So when I try to read userInfo, it failed.

Now I use:

```js

  QuickActions
    .popInitialAction()
    .then(handlePopInitialAction)

function handlePopInitialAction(data) {
  // items is an array contains quick actions.
  if (isAndroid && data && data.type && _.isString(data.type)) {
    data = items.find(item => item.type === data.type)
  }
  handleEvents(data)
}
```
